# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations. Please make changes
# to configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-e6828f57-55f3-43b4-a7ad-99541f6a2fa4";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-e6828f57-55f3-43b4-a7ad-99541f6a2fa4".device =
    "/dev/disk/by-uuid/e6828f57-55f3-43b4-a7ad-99541f6a2fa4";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-e6828f57-55f3-43b4-a7ad-99541f6a2fa4";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-e6828f57-55f3-43b4-a7ad-99541f6a2fa4";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7DDC-9007";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-8831e440-bd59-4465-b1fe-af738d91cab2"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
